version: "3.10"

services:
  bot-pos:
    build:
      context: ./pos/
      dockerfile: Dockerfile
    container_name: aiogram_bot_linzy_pos
    restart: always
    volumes:
      - ./evacuation.db:/app/evacuation.db
      - .:/app  # Остальной код проекта