version: "3.10"

services:
  bot-pos:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: araba_bot
    restart: always
    volumes:
      - ./evacuation.db:/app/evacuation.db
      - .:/app  # Остальной код проекта